/**
 * generate-sitemap.js
 *
 * Fetches published books and projects from Firestore REST API and writes
 * public/sitemap.xml before the Vite build. Runs on every `npm run build`.
 *
 * No SDK or extra dependencies required — uses Node's native fetch (Node 18+).
 * Falls back to a minimal sitemap if Firestore is unreachable.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load .env for local dev (Netlify injects env vars automatically in CI)
try {
  const envPath = path.join(__dirname, '../.env');
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx < 1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim().replace(/^["']|["']$/g, '');
      if (!process.env[key]) process.env[key] = val;
    }
  }
} catch { /* silent */ }

const PROJECT_ID = process.env.VITE_FIREBASE_PROJECT_ID;
const BASE_URL   = 'https://desk-of-saar.netlify.app';
const FIRESTORE  = `https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents`;

function field(doc, key) {
  const f = doc.fields?.[key];
  if (!f) return null;
  return f.stringValue ?? (f.booleanValue !== undefined ? f.booleanValue : null) ?? f.integerValue ?? null;
}

function xmlEscape(str) {
  return String(str || '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function fetchDocs(collection) {
  const url = `${FIRESTORE}/${collection}?pageSize=200`;
  const res = await fetch(url, { signal: AbortSignal.timeout(8000) });
  if (!res.ok) throw new Error(`Firestore ${collection}: HTTP ${res.status}`);
  const json = await res.json();
  return json.documents || [];
}

async function run() {
  const today = new Date().toISOString().split('T')[0];
  let books = [];
  let projects = [];

  if (!PROJECT_ID) {
    console.warn('[sitemap] VITE_FIREBASE_PROJECT_ID not set — generating minimal sitemap.');
  } else {
    try {
      const [rawBooks, rawProjects] = await Promise.all([
        fetchDocs('books'),
        fetchDocs('projects'),
      ]);
      books    = rawBooks.filter(d => field(d, 'published') === true);
      projects = rawProjects.filter(d => field(d, 'published') === true);
      console.log(`[sitemap] Fetched ${books.length} book(s), ${projects.length} project(s) from Firestore.`);
    } catch (err) {
      console.warn(`[sitemap] Firestore fetch failed (${err.message}) — generating minimal sitemap.`);
    }
  }

  // Collect all cover/thumbnail images for the image sitemap extension
  const images = [
    { url: `${BASE_URL}/saar_img.jpeg`, title: 'Omar Rashid Lone — Author and Developer' },
    ...books
      .map(d => field(d, 'coverUrl'))
      .filter(Boolean)
      .map(url => ({ url, title: xmlEscape(field(books.find(d => field(d, 'coverUrl') === url), 'title') || 'Book cover') })),
    ...projects
      .map(d => field(d, 'thumbnailUrl'))
      .filter(Boolean)
      .map(url => ({ url, title: xmlEscape(field(projects.find(d => field(d, 'thumbnailUrl') === url), 'title') || 'Project thumbnail') })),
  ];

  const imageXml = images
    .map(img => `    <image:image>\n      <image:loc>${img.url}</image:loc>\n      <image:title>${img.title}</image:title>\n    </image:image>`)
    .join('\n');

  // Build book + project keyword lists for the <news:keywords> hint (optional, harmless if absent)
  const bookTitles    = books.map(d => xmlEscape(field(d, 'title')    || '')).filter(Boolean);
  const projectTitles = projects.map(d => xmlEscape(field(d, 'title') || '')).filter(Boolean);

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

  <!--
    Auto-generated by scripts/generate-sitemap.js at build time.
    Books  : ${bookTitles.join(', ') || 'none'}
    Projects: ${projectTitles.join(', ') || 'none'}
  -->

  <url>
    <loc>${BASE_URL}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
${imageXml}
  </url>

</urlset>
`;

  const outPath = path.join(__dirname, '../public/sitemap.xml');
  fs.writeFileSync(outPath, sitemap.trim() + '\n', 'utf-8');
  console.log(`[sitemap] ✓ Written to public/sitemap.xml (${images.length} image(s))`);
}

run().catch(err => {
  // Never let sitemap failure break the build
  console.error('[sitemap] Unexpected error:', err.message);
});
